### ISSUE TITLE
com.mysql.cj.core.exceptions.WrongArgumentException: Connector/J cannot handle a database URL of type 'jdbc:postgresql:'

### ISSUE THREAD

**Issue by ffauteux** [osiam/performance-tests#14]
Running `mvn clean verify` on Centos 7 using:
docker-ce-17.06.1.ce-1.el7.centos.x86_64
jdk1.8.0_121-1.8.0_121-fcs.x86_64
apache-maven-3.5.0-bin.tar.gz

The following error occurs:

[INFO] [INFO] 2017-09-01 13:33:56,848 org.osiam.tests.performance.PerformanceTestContext - Setting up database
[INFO] [INFO] 2017-09-01 13:33:56,856 org.osiam.tests.performance.tools.TestDataCreation - Start database setup
[INFO] com.mysql.cj.core.exceptions.WrongArgumentException: Connector/J cannot handle a database URL of type 'jdbc:postgresql:'.
[INFO] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[INFO] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[INFO] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[INFO] 	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:54)
[INFO] 	at com.mysql.cj.core.conf.url.ConnectionUrl$Type.fromValue(ConnectionUrl.java:149)
[INFO] 	at com.mysql.cj.core.conf.url.ConnectionUrl.getConnectionUrlInstance(ConnectionUrl.java:193)
[INFO] 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:195)
...

See full output:
[mvn_clean_verify.txt](https://github.com/osiam/performance-tests/files/1270581/mvn_clean_verify.txt)

Could this be related to: https://bugs.mysql.com/bug.php?id=82896

**Comment by ffauteux** [comment]
Full exception stack trace:

[INFO] [ERROR] 2017-09-01 16:53:44,826 org.osiam.tests.performance.tools.TestDataCreation - org.dbunit.dataset.DataSetException: java.sql.SQLSyntaxErrorException: Unknown table 'osiam_client' in information_schema
[INFO] 	at org.dbunit.database.DatabaseTableMetaData.getPrimaryKeys(DatabaseTableMetaData.java:392)
[INFO] 	at org.dbunit.operation.AbstractOperation.getOperationMetaData(AbstractOperation.java:95)
[INFO] 	at org.dbunit.operation.AbstractBatchOperation.execute(AbstractBatchOperation.java:150)
[INFO] 	at org.dbunit.operation.CompositeOperation.execute(CompositeOperation.java:79)
[INFO] 	at org.osiam.tests.performance.tools.TestDataCreation.setupDatabase(TestDataCreation.java:88)
[INFO] 	at org.osiam.tests.performance.PerformanceTestContext.<clinit>(PerformanceTestContext.java:49)
[INFO] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[INFO] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[INFO] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[INFO] 	at org.apache.jmeter.protocol.java.sampler.JUnitSampler.getClassInstance(JUnitSampler.java:532)
[INFO] 	at org.apache.jmeter.protocol.java.sampler.JUnitSampler.initializeTestObject(JUnitSampler.java:656)
[INFO] 	at org.apache.jmeter.protocol.java.sampler.JUnitSampler.threadStarted(JUnitSampler.java:644)
[INFO] 	at org.apache.jmeter.threads.JMeterThread$ThreadListenerTraverser.addNode(JMeterThread.java:647)
[INFO] 	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:996)
[INFO] 	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:978)
[INFO] 	at org.apache.jmeter.threads.JMeterThread.threadStarted(JMeterThread.java:616)
[INFO] 	at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:604)
[INFO] 	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:237)
[INFO] 	at java.lang.Thread.run(Thread.java:748)
[INFO] Caused by: java.sql.SQLSyntaxErrorException: Unknown table 'osiam_client' in information_schema
[INFO] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:560)
[INFO] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:537)
[INFO] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:527)
[INFO] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
[INFO] 	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2011)
[INFO] 	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1964)
[INFO] 	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
[INFO] 	at com.mysql.cj.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3182)
[INFO] 	at com.mysql.cj.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3170)
[INFO] 	at com.mysql.cj.jdbc.IterateBlock.doForAll(IterateBlock.java:50)
[INFO] 	at com.mysql.cj.jdbc.DatabaseMetaData.getPrimaryKeys(DatabaseMetaData.java:3223)
[INFO] 	at org.dbunit.database.DefaultMetadataHandler.getPrimaryKeys(DefaultMetadataHandler.java:147)
[INFO] 	at org.dbunit.database.DatabaseTableMetaData.getPrimaryKeyNames(DatabaseTableMetaData.java:224)
[INFO] 	at org.dbunit.database.DatabaseTableMetaData.getPrimaryKeys(DatabaseTableMetaData.java:386)
[INFO] 	... 19 more

**Comment by dacrome** [comment]
Hi @ffauteux 

thanks for running the performance-tests and creating this issue. We are investigating in this in the next days.

Greetz,
David

**Comment by dacrome** [comment]
Hi @ffauteux 

I updated this project and the build is green now on CircleCI.
Can you re-run it on your machine again?

But it should not fix your problem:
```
[INFO] com.mysql.cj.core.exceptions.WrongArgumentException: Connector/J cannot handle a database URL of type 'jdbc:postgresql:'.
```
If running against a MySQL, the URL should not start with `jdbc:postgresql`.
Can you please check your configuration?

Greetz,
David

**Comment by ffauteux** [comment]
Ran 'mvn clean verify' against the new code base, obtained docker error (see attachment).

[mvn_clean_verify_updated.txt](https://github.com/osiam/performance-tests/files/1277489/mvn_clean_verify_updated.txt)

**Comment by ffauteux** [comment]
Apologies, closed this issue by mistake.

**Comment by ffauteux** [comment]
Have had to revert some recent changes in pom.xml, perhaps the updated docker-maven-plugin is incompatible with docker-ce-17.06.1.ce-1.el7.centos.x86_64?

        
        <docker.host>http://localhost:2375</docker.host>
        <docker.removeIntermediateImages>true</docker.removeIntermediateImages>

        <version.spring>4.3.10.RELEASE</version.spring>
        <version.docker-maven-plugin>2.10.6</version.docker-maven-plugin>

**Comment by ffauteux** [comment]
Regarding this problem:

    [INFO] com.mysql.cj.core.exceptions.WrongArgumentException: Connector/J cannot handle a database URL of type 'jdbc:postgresql:'.

It seems commenting out the following in pom.xml removes the error (for the previous version of the project, not the recent one):

        

With a reduced number of users (100) and groups (5), the test run results are:

    [INFO] summary +    213 in 00:01:40 =    2.1/s Avg:   107 Min:     9 Max:   439 Err:     0 (0.00%) Active: 1 Started: 6 Finished: 5
    [INFO] summary +    200 in 00:00:05 =   42.8/s Avg:    22 Min:     6 Max:   435 Err:     1 (0.50%) Active: 0 Started: 0 Finished: 0
    [INFO] summary =    413 in 00:01:45 =    3.9/s Avg:    66 Min:     6 Max:   439 Err:     1 (0.24%)

I assume the error is an OSIAM issue, not a performance test issue.

**Comment by dacrome** [comment]
Hi @ffauteux 

> Have had to revert some recent changes in pom.xml, perhaps the updated docker-maven-plugin is incompatible with docker-ce-17.06.1.ce-1.el7.centos.x86_64?

did you change your DOCKER_OPTS like this? https://github.com/osiam/performance-tests/blob/master/circle.yml#L9

**Comment by dacrome** [comment]
but the tests are running on CircleCi: https://circleci.com/gh/osiam/performance-tests/61

The mysql connector should only be used when running with the mysql Maven profile.

**Comment by ffauteux** [comment]
I changed the DOCKER_OPTS via the /usr/lib/systemd/system/docker.service file (adapted from the README, as I'm running on Centos 7):

    [Service]
    ...
    ExecStart=/usr/bin/dockerd -H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock

**Comment by ffauteux** [comment]
Regarding the mysql connector, it seems that simply including it as a project dependency is causing a problem, even though it's not actually used. I don't know what Maven is doing under the hood (possibly related to https://bugs.mysql.com/bug.php?id=82896), but it appears the dependency itself should be conditional.

**Comment by dacrome** [comment]
Is it fixed with your fix mentioned in #15 ?

**Comment by ffauteux** [comment]
No, #15 is a different issue. This issue (#14) seems aesthetic, the tests are able to run successfully.

**Comment by dacrome** [comment]
thanks for your issue, but this repository will be archived.
