### ISSUE TITLE
java.sql.SQLSyntaxErrorException: Unknown table 'osiam_client' in information_schema

### ISSUE THREAD

**Issue by ffauteux** [osiam/performance-tests#15]
Running `mvn clean verify -P mysql` on Centos 7 using:
docker-ce-17.06.1.ce-1.el7.centos.x86_64
jdk1.8.0_121-1.8.0_121-fcs.x86_64
apache-maven-3.5.0-bin.tar.gz

The following error occurs:

[INFO] [INFO] 2017-09-01 14:48:25,898 org.osiam.tests.performance.tools.TestDataCreation - Start database setup
[INFO] [ERROR] 2017-09-01 14:48:27,941 org.osiam.tests.performance.tools.TestDataCreation - java.sql.SQLSyntaxErrorException: Unknown table 'osiam_client' in information_schema
[INFO] [INFO] 2017-09-01 14:48:27,942 org.osiam.tests.performance.tools.TestDataCreation - Finished database setup

Full output: [mvn_clean_verify_p_mysql.txt](https://github.com/osiam/performance-tests/files/1270627/mvn_clean_verify_p_mysql.txt)

**Comment by ffauteux** [comment]
Full exception stack trace:

[INFO] [ERROR] 2017-09-01 16:53:44,826 org.osiam.tests.performance.tools.TestDataCreation - org.dbunit.dataset.DataSetException: java.sql.SQLSyntaxErrorException: Unknown table 'osiam_client' in information_schema
[INFO] at org.dbunit.database.DatabaseTableMetaData.getPrimaryKeys(DatabaseTableMetaData.java:392)
[INFO] at org.dbunit.operation.AbstractOperation.getOperationMetaData(AbstractOperation.java:95)
[INFO] at org.dbunit.operation.AbstractBatchOperation.execute(AbstractBatchOperation.java:150)
[INFO] at org.dbunit.operation.CompositeOperation.execute(CompositeOperation.java:79)
[INFO] at org.osiam.tests.performance.tools.TestDataCreation.setupDatabase(TestDataCreation.java:88)
[INFO] at org.osiam.tests.performance.PerformanceTestContext.(PerformanceTestContext.java:49)
[INFO] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[INFO] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[INFO] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[INFO] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[INFO] at org.apache.jmeter.protocol.java.sampler.JUnitSampler.getClassInstance(JUnitSampler.java:532)
[INFO] at org.apache.jmeter.protocol.java.sampler.JUnitSampler.initializeTestObject(JUnitSampler.java:656)
[INFO] at org.apache.jmeter.protocol.java.sampler.JUnitSampler.threadStarted(JUnitSampler.java:644)
[INFO] at org.apache.jmeter.threads.JMeterThread$ThreadListenerTraverser.addNode(JMeterThread.java:647)
[INFO] at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:996)
[INFO] at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:978)
[INFO] at org.apache.jmeter.threads.JMeterThread.threadStarted(JMeterThread.java:616)
[INFO] at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:604)
[INFO] at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:237)
[INFO] at java.lang.Thread.run(Thread.java:748)
[INFO] Caused by: java.sql.SQLSyntaxErrorException: Unknown table 'osiam_client' in information_schema
[INFO] at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:560)
[INFO] at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:537)
[INFO] at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:527)
[INFO] at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
[INFO] at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2011)

**Comment by dacrome** [comment]
I think this is a followup error of a wrong configuration mentioned in #14 ... it looks like OSIAM did not create the DB schema, so maybe it did not start.

**Comment by ffauteux** [comment]
The output of the tomcat Docker shows that OSIAM is being started:

    [INFO] STDOUT: 2017-09-06 18:46:19.830  INFO 1 --- [ost-startStop-1] org.osiam.Osiam                          : Starting Osiam on 56b271c86163 with PID 1 (/usr/local/tomcat/webapps/osiam/WEB-INF/classes started by root in /usr/local/tomcat)
    [INFO] STDOUT: 2017-09-06 18:46:19.837  INFO 1 --- [ost-startStop-1] org.osiam.Osiam                          : No active profile set, falling back to default profiles: default
    [INFO] STDOUT: 2017-09-06 18:46:20.177  INFO 1 --- [ost-startStop-1] org.osiam.OsiamHome                      : osiam.home = /var/lib/osiam
    [INFO] STDOUT: 2017-09-06 18:46:42.996  INFO 1 --- [ost-startStop-1] org.osiam.ExampleData                    : Created OAuth client 'example-client' with secret 'secret'
    [INFO] STDOUT: 2017-09-06 18:46:43.753  INFO 1 --- [ost-startStop-1] org.osiam.ExampleData                    : Created admin user 'admin' with password 'koala' and id 'bdd0163e-8664-4ec7-a9e5-2796c0ac52f9'
    [INFO] STDOUT: 2017-09-06 18:46:44.306  WARN 1 --- [ost-startStop-1] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class org.osiam.scim.extension.ExtensionsConfiguration contains validation constraints but had not been annotated with @Validated.
    [INFO] STDOUT: 2017-09-06 18:46:44.306  WARN 1 --- [ost-startStop-1] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class org.osiam.scim.extension.ExtensionsConfiguration contains validation constraints but had not been annotated with @Validated.
    [INFO] STDOUT: 2017-09-06 18:46:44.307  WARN 1 --- [ost-startStop-1] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class org.osiam.scim.extension.ExtensionsConfiguration contains validation constraints but had not been annotated with @Validated.
    [INFO] STDOUT: 2017-09-06 18:46:47.874  INFO 1 --- [ost-startStop-1] org.osiam.Osiam                          : Started Osiam in 28.707 seconds (JVM running for 38.976)

From what I can tell, this is an issue different from [#14](https://github.com/osiam/performance-tests/issues/14).

**Comment by ffauteux** [comment]
Further diagnostic information: modified the suite to communicate with an outside OSIAM instance:

* Removed contents of src/main/docker/
* Modified src/main/resources/performance-tests_mysql.properties to talk to DB on 3306
* Modified src/main/java/org/osiam/tests/performance/PerformanceTestContext.java to talk to OSIAM via 8080

OSIAM starts up normally

mysql DB shows correct tables:

    [root@user]# /usr/bin/mysql -u osiam -p 
    mysql> show tables in osiam;
    +----------------------------+
    | Tables_in_osiam            |
    +----------------------------+
    | osiam_client               |
    | osiam_client_grants        |
    | osiam_client_scopes        |
    | schema_version             |
    | scim_address               |
    | scim_certificate           |
    | scim_email                 |
    | scim_entitlements          |
    | scim_extension             |
    | scim_extension_field       |
    | scim_extension_field_value |
    | scim_group                 |
    | scim_group_members         |
    | scim_id                    |
    | scim_im                    |
    | scim_meta                  |
    | scim_name                  |
    | scim_phonenumber           |
    | scim_photo                 |
    | scim_roles                 |
    | scim_user                  |
    +----------------------------+
    21 rows in set (0.00 sec)

Same issue: Unknown table 'osiam_client' in information_schema

**Comment by dacrome** [comment]
Hi @ffauteux 

so you are starting OSIAM and MySQL not in Docker?
Did you set the correct connection data for you local running OSIAM in `/var/lib/osiam`?

**Comment by ffauteux** [comment]
I've tried both methods: running OSIAM+MySQL in Docker (as implemented in the suite), and running OSIAM+MySQL natively in my host (with osiam.yaml properly modified to use MySQL).

In both cases, the issue is the same. The OSIAM running natively starts up normally and creates the appropriate tables. I wanted to verify whether it could be a misconfiguration of the OSIAM running in Docker, but it seems not to be the case. I assume this points to an issue with the Performance Test suite data creation logic. I'll see if I can troubleshoot this further.

**Comment by ffauteux** [comment]
Would it be possible to submit a full TRACE log (as per logback.xml) of a successful run for me to compare against my own output?

I've produced this TRACE log with the penultimate version of pom.xml: [mvn_clean_mysql_trace.txt](https://github.com/osiam/performance-tests/files/1285898/mvn_clean_mysql_trace.txt)

**Comment by ffauteux** [comment]
Have found a workaround for the issue; in pom.xml:

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            
            <version>5.1.44</version>
        </dependency>

And in src/main/resources/performance-tests_mysql.properties:

  # org.osiam.performance-tests.db.driver=com.mysql.cj.jdbc.Driver
  org.osiam.performance-tests.db.driver=com.mysql.jdbc.Driver

I tried this configuration based on the current connector4java-integration-tests pom.xml.

**Comment by dacrome** [comment]
Hi @ffauteux 

cool. Can you create a pull request?

Regards,
David

**Comment by ffauteux** [comment]
If the new mysql-connector-java version (6.0.4) is working in your environment, I don't know if a change is required. Perhaps this issue is enough to document the problem and have other people encountering it apply the same workaround. I've documented the details of my environment in the original description.

**Comment by dacrome** [comment]
thanks for your issue, but this repository will be archived.
